### ISSUE TITLE
BUG : Breaking changes for version 2.4.3

### ISSUE THREAD

**Issue by amd-wso** [rudderlabs/rudder-sdk-ios#449]
**Describe the bug**
After migrating from version 2.4.2 -> 2.4.3 Xcode is giving many syntax errors.

If using v1 Documentation, it satisfies the warnings but it doesn't seem right

**Screenshots**
<img width="920" alt="Screenshot 2024-01-26 at 12 41 15 PM" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/157831078/c299e4f0-b2c1-443a-8a15-26d7095845a1">

**Version of the _iOS_ SDK**
iOS SDK v2.4.3

**Comment by desusai7** [comment]
Hello @amd-wso, 

This is working as expected for us. Can you please verify if the version of the SDK you are using is `2.4.3`?

Also how were you integrating the SDK, is it via Cocoapods or SPM ?

**Comment by amd-wso** [comment]
Hi @desusai7 ,

I'm using SPM. The package shows it's version 2.4.3

<img width="188" alt="image" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/157831078/190f6721-5b8c-432a-a4ce-585e6bcdee69">

**Comment by desusai7** [comment]
@amd-wso, Can you please try clearing the cache and downloading the package again?

There seems to be an issue with the tags, fixed it now.

**Comment by garethlloyd1994** [comment]
We are also seeing this issue, seems there is a mismatch between our local machines and CI which is failing. 

Made the changes to fix the breaking changes to the code, which works locally but fails everytime on CI.

Tried clearing cache and downloading again with no success.

**Comment by desusai7** [comment]
Hey @garethlloyd1994, 

We had an issue with our CI pipeline, because of which the tag 2.4.3 used when downloading our package via SPM is pointing to the v1 source code instead of the v2 source code.

We have now rectified this issue and tag 2.4.3 points to the v2 source code; hence, there are no breaking changes now. It seems like your CI is now downloading the updated tag via SPM, so it is failing. Your local machine has the faulty tag, so it is working fine for you locally.

Apologies for this issue. We are working on fixing it and will ensure that this will not happen again.

**Comment by garethlloyd1994** [comment]
Thanks for the update @desusai7 - We have reverted to point directly at 2.4.2 for the moment as a workaround. If you can let me know when the issue is fully resolved and i'll update the package!

**Comment by desusai7** [comment]
@garethlloyd1994, this is fixed now. Can you please try clearing cache and check this again ?

**Comment by sslash** [comment]
I'm still having this issue, using SPM. Cleared cache etc.

<img width="1233" alt="image" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/1174520/1b0c43d7-a8af-40ba-ac03-aef7d33e42d6">

**Comment by desusai7** [comment]
@sslash, apologies for this. we've found one more faulty tag and fixed it right now. Can you please clear the cache and try it again ?

**Comment by sslash** [comment]
@desusai7 

Seeing this issue now when I try to add it again:

<img width="849" alt="image" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/1174520/710540f4-415e-41ff-9543-ec1a9a66a90c">

**Comment by vg-identance** [comment]
Currently can't install 2.4.3 via pods.
![Screenshot 2024-03-28 at 18 26 12](https://github.com/rudderlabs/rudder-sdk-ios/assets/49786280/85ea5610-e399-430e-bbfd-5f708d057c9a)

**Comment by desusai7** [comment]
Hi @sslash, 

We've updated all the tags of 2.4.3 to point to the correct commits and it is working as expected for us. Attaching a screenshot of the same below. It might be a cache issue, Can you please try clearing it once more and check it out ?
<img width="1728" alt="image" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/48179357/d59b8a90-66bc-4682-8900-3c600b24edf4">

**Comment by desusai7** [comment]
@vg-identance, this issue has been resolved now. Could you please try downloading it again?

@amd-wso, @garethlloyd1994, @sslash, @vg-identance, iOS SDK v2 is still in beta, and there may be a few issues like this one that we are actively working on to fix. Please migrate to iOS SDK v1 to ensure consistent and stable behavior.

**Comment by sslash** [comment]
@desusai7 The reason I use V2 is because I reached out on Slack regarding an issue with V1 earlier, and was advised by someone from the RudderStack team to use V2. It was not mentioned that V2 was in beta.

I'm still getting the same issue after resetting cache. I've tried both deleting it from `open ~/Library/Caches/org.swift.swiftpm/repositories` and done `file > packages > reset packages cache`

thanks

**Comment by sslash** [comment]
@desusai7 I went back to this again now, and I got 2.4.3 correctly installed.  Nice! 👍

However, I'm not getting any of my custom events sent. I'm just doing a simple test, e.g:
```
let config: RSConfig = RSConfig(writeKey: MyRudderstackWriteKey)
            .dataPlaneURL(myRudderstackDataPlaneurl)
            .trackLifecycleEvents(true)
            .loglevel(.debug)
            .recordScreenViews(false)
        
        
        RSClient.sharedInstance().configure(with: config)


RSClient.sharedInstance().track("my event name")

```

And the event does not get picked up.

Here's a screenshot:

<img width="980" alt="image" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/1174520/d00b69a1-0f78-45a5-b774-4fe92cf765b5">


Cheers!

**Comment by desusai7** [comment]
@sslash, I am no longer the maintainer of this repository.

Tagging @ChryssaAliferi, @1abhishekpandey to assist you further on this.

**Comment by 1abhishekpandey** [comment]
Hey @sslash,
First of all, apologies if someone has asked to move to v2. I would kindly request you to consider reverting back to v1, as v2 is still in beta.

Regarding your issue, I attempted to replicate the exact scenario you described. Initially, I triggered an event immediately after initializing the SDK, and subsequently, I triggered another event using a button. I successfully observed both events in the RudderStack dashboard:
<img width="861" alt="image" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/64667840/d3ed808c-8e25-48c8-88ac-ac95fba8916c">

I would kindly request you to check a couple of things:
- Place a debug breakpoint where you're triggering the following event using the button, and attempt to `step into` the `track` API to verify if the control reaches that point or not:
```
// Triggered later from somewhere else in app (just a button tap), will not be picked up...
RSClient.sharedInstance().track("my event name")
```
- Next, install the app fresh (i.e., uninstall it completely and then reinstall it), and please share the complete Rudder SDK log.

**Comment by sslash** [comment]
@1abhishekpandey I just downgraded to 1.26.3 and events are tracking correctly there.

Thanks!
